apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/ermias-biz/capstone-project-cluster-prod-frontend:latest
          ports:
            - containerPort: 5000
          command: ["npm"]
          args: ["run", "start"]
          imagePullPolicy: Always
          env:
            - name: REACT_APP_MAPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mapbox-token
                  key: REACT_APP_MAPBOX_ACCESS_TOKEN