apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/ermias-biz/capstone-project-cluster-frontend:latest
          ports:
            - containerPort: 5000
          command: ["npm"]
          args: ["run", "start"]
          imagePullPolicy: Always