apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5000
    - port : 443
      name: https
      protocol: TCP
      targetPort: 5000
  selector:
    run: frontend
  type: NodePort
#  loadBalancerIP: 34.149.74.164